/* dv-scripts.js
 * https://mouseypounds.github.io/dappervolk/
 */

/*jslint indent: 4, maxerr: 50, passfail: false, browser: true, regexp: true, plusplus: true */

window.onload = function () {
	"use strict";

	// Utility functions
	function addCommas(x) {
		// Jamie Taylor @ https://stackoverflow.com/questions/3883342/add-commas-to-a-number-in-jquery
		return x.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g, ",");
	}

	// Because we added commas to make the numbers look pretty, we want an easy way to strip them too
	// We will also convert this back to an integer since that is what we want when doing this.
	function removeCommas(x) {
		x = x.replace(/\,/g, '');
		return parseInt(x, 10);
	}
	
	// If 2 args, interpreted as (min, max) with range [min, max)
	// If 1 arg, interpreted as (max) with range [0, max)
	function randInt(a, b) {
		var min, max;
		if (b === undefined) {
			min = 0;
			max = a;
		} else {
			min = a;
			max = b;
		}	
		return Math.floor(min + Math.random()*(max - min));
	}
	
	function generateList() {
		var howMany = document.getElementById("item_count").value;
		var whichClass = document.getElementById("class_specific").value;
		var townAlch = $("#extra_alch").prop('checked');
		var townAff = $("#extra_aff").prop('checked');
		
		pickFrom = [];
		$('.check_sub').each(function() {
			if ($(this).prop('checked')) {
				pickFrom.push.apply(pickFrom, clothes[$(this).attr("name")]);
				if ($(this).hasClass('town')) {
					if (townAlch) { pickFrom.push.apply(pickFrom, extra_alch[$(this).attr("name")]); }
					if (townAff) { pickFrom.push.apply(pickFrom, extra_aff[$(this).attr("name")]); }
				}
			}
		});
		if (whichClass !== "none") {
			pickFrom.push.apply(pickFrom, clothes[whichClass]);
		}
		
		var output = "<p>Picking " + howMany + " random items from a pool of " + pickFrom.length + ":</p>";
		var theItems = [];
		if (howMany <= pickFrom.length) {
			output += "<ol>";
			for (var i = 0; i < howMany; i++) {
				var index = -1;
				while (index === -1 || theItems.includes(index)) {
					index = randInt(pickFrom.length);
				}
				theItems.push(index);
				output += "<li>" + pickFrom[index] + "</li>";
			}
			output += "</ol>";
		} else {
			output += '<p class="note">Cannot generate item list because pool is too small</p>';
		}
		
		setCookies();
		document.getElementById("output-container").innerHTML = output;
	}

	function setCookies() {
		$('input:checkbox').each(function() {
			var n = $(this).attr("name");
			Cookies.set(n, $(this).prop('checked'), { expires: 365, path: '' });
		});
		$('select').each(function() {
			var n = $(this).attr("name");
			Cookies.set(n, $(this).val(), { expires: 365, path: '' });
		});
		
	}
	
	function setCheckboxes(on) {
		$('input:checkbox').each(function() {
			$(this).prop('checked', on);
		});
	}
	
	$( document ).ready(function() {
		// Restore prefs from cookies
		$('input:checkbox').each(function() {
			var n = $(this).attr("name");
			var c = Cookies.get(n);
			if (typeof(c) !== 'undefined') {
				$(this).prop('checked', (c === "true"));
			}
		});
		$('select').each(function() {
			var n = $(this).attr("name");
			var c = Cookies.get(n);
			if (typeof(c) !== 'undefined') {
				$(this).val(c);
			}
		});
		
		document.getElementById("button_all_on").addEventListener("click", function() { setCheckboxes(1) } );
		document.getElementById("button_all_off").addEventListener("click", function() { setCheckboxes(0) } );
		document.getElementById("theButton").addEventListener("click", function() { generateList(); } );
	});

	var clothes = {
		"pr_alpha": [
			"Support Axe",
			"Support Bun",
		],
		"pr_beta": [
			"Druid's Vine Hairstyle",
			"Druid's Vine Shoes",
			"Druid's Vine Staff",
			"Musician's Potion Coat",
			"Musician's Teal Hairstyle",
			"Musician's Winged Cello",
		],
		"pr_ks": [
			"Aquarium Fish",
			"Aquarium Memory",
			"Gem Serpent",
			"Gold Fish",
			"Golden Aquarium Background",
			"Golden Aquarium Skin",
			"Golden Kelp Veil",
			"Golden Sea Bob",
			"Golden Sea Dress",
			"Golden Sea Locks",
			"Golden Sea Pantaloons",
			"Golden Smile",
			"Jeweled Bob",
			"Jeweled Braids",
			"Jeweled Coat",
			"Jeweled Gaze",
			"Jeweled Lips",
			"Jeweled Sky Background",
			"Jeweled Trousers",
			"Jeweled Unicorn Crown",
			"Jeweled Unicorn Legs",
			"Jeweled Unicorn Tail",
			"Jeweled Unicorn Wings",
			"Jeweled Wings Skin",
			"Obsidian Bob",
			"Obsidian Boots",
			"Obsidian Cape",
			"Obsidian Dragon Tail",
			"Obsidian Dragon Wings",
			"Obsidian Flowing Locks",
			"Obsidian Gem Horns",
			"Obsidian Gem Tunic",
			"Obsidian Leer",
			"Obsidian Lips",
			"Obsidian Skin",
			"Pearlescent Pony",
		],
		"pr_launch": [
			"Celestial Bob Hairstyle",
			"Celestial Cat",
			"Celestial Chestplate",
			"Celestial Cuirass",
			"Celestial Egg",
			"Celestial Pigtails",
			"Celestial Skirt",
			"Celestial Trousers",
			"Draconic Bob Hair",
			"Draconic Cat",
			"Draconic Chestplate",
			"Draconic Cuirass",
			"Draconic Pigtails",
			"Draconic Skirt",
			"Draconic Trousers",
		],
		"town_lh": [
			"Bearnard's Broom",
			"Bearnard's Dark Farming Gloves",
			"Bearnard's Dark Farming Shirt",
			"Bearnard's Dark Farming Shoes",
			"Bearnard's Farming Gloves",
			"Bearnard's Farming Overalls",
			"Bearnard's Farming Shirt",
			"Bearnard's Farming Shoes",
			"Bearnard's Green Farming Overalls",
			"Bearnard's Green Ribbon Broom",
			"Bearnard's Green Ribbon Sun Hat",
			"Bearnard's Sun Hat",
			"Buli's Essence Rings",
			"Buli's Essence Spirit",
			"Buli's Green Essence Rings",
			"Buli's Green Essence Spirit",
			"Buli's Hairstyle Brown",
			"Buli's Hairstyle",
			"Buli's Magic Green Pots",
			"Buli's Magic Pots",
			"Buli's Mysterious Dark Dress",
			"Buli's Mysterious Dress",			
			"Calbet's Archery Boots",
			"Calbet's Armour",
			"Calbet's Cabbage Friend",
			"Calbet's Hairstyle Orange",
			"Calbet's Hairstyle",
			"Calbet's Orange Cabbage Friend",
			"Calbet's Pantaloons",
			"Calbet's Red Archery Boots",
			"Calbet's Red Armour",
			"Calbet's Red Pantaloons",
			"Calbet's Red Training Quiver",
			"Calbet's Rowan Training Bow",
			"Calbet's Training Bow",
			"Calbet's Training Quiver",
			"Fantasia's Cold Eyepatch",
			"Fantasia's Dagger Gloves",
			"Fantasia's Desert Halo",
			"Fantasia's Eyepatch",
			"Fantasia's Fox Tail",
			"Fantasia's Green Dagger Gloves",
			"Fantasia's Green Desert Halo",
			"Fantasia's Green Fox Tail",
			"Fantasia's Green Rogue Boots",
			"Fantasia's Green Training Shirt",
			"Fantasia's Hairstyle Green",
			"Fantasia's Hairstyle",
			"Fantasia's Rogue Boots",
			"Fantasia's Training Shirt",
			"Lilia's Battle Tiara",
			"Lilia's Cold Gauntlets",
			"Lilia's Flower Gem Necklace",
			"Lilia's Gauntlets",
			"Lilia's Hairstyle Ice",
			"Lilia's Hairstyle",
			"Lilia's Ice Battle Tiara",
			"Lilia's Ice Flower Gem Necklace",
			"Lilia's Ice Training Armor",
			"Lilia's Soldier Leggings",
			"Lilia's Steel Soldier Leggings",
			"Lilia's Steel Training Lances",
			"Lilia's Training Armor",
			"Lilia's Training Lances",		
			"Not A Wizard Hairstyle",
			"Not A Wizard Hat",
			"Not A Wizard Peach Hairstyle",
			"Not A Wizard Red Hat",
			"Not A Wizard Red Robe Drapings",
			"Not A Wizard Red Robe Top",
			"Not A Wizard Red Trinket",
			"Not A Wizard Robe Drapings",
			"Not A Wizard Robe Top",
			"Not A Wizard Silver Wand",
			"Not A Wizard Trinket",
			"Not A Wizard Wand",
			"Not Wizard Keys",
			"Not Wizard Silver Keys",
		],
		"town_3f": [
			"Barclay's Belts",
			"Barclay's Flower Mantle",
			"Barclay's Flower Puppet",
			"Barclay's Garland",
			"Barclay's Hairstyle White",
			"Barclay's Hairstyle",
			"Barclay's Indignance",
			"Barclay's Lip",
			"Barclay's Pale Belts",
			"Barclay's Pale Indignance",
			"Barclay's Pale Lip",
			"Barclay's Pale Sweater",
			"Barclay's Pale Trousers",
			"Barclay's Ragged Blue Cape",
			"Barclay's Ragged Cape",
			"Barclay's Sweater",
			"Barclay's Trousers",
			"Barclay's White Flower Mantle",
			"Barclay's White Flower Puppet",
			"Barclay's White Garland",			
			"Glume's Bone Dress",
			"Glume's Ferocity",
			"Glume's Hairstyle Ombre Orange",
			"Glume's Hairstyle",
			"Glume's Lace Headdress",
			"Glume's Lace Warm Headdress",
			"Glume's Lip",
			"Glume's Loop Scarf",
			"Glume's Orange Bone Dress",
			"Glume's Orange Ferocity",
			"Glume's Orange Lip",
			"Glume's Orange Thorn Pouch",
			"Glume's Orange Vine Chain",
			"Glume's Orange Vine Shoes",
			"Glume's Rose Eyepatch",
			"Glume's Thorn Pouch",
			"Glume's Vine Chain",
			"Glume's Vine Shoes",
			"Glume's Warm Loop Scarf",
			"Glume's Warm Rose Eyepatch",
			"Irin's Blue Floral Pants",
			"Irin's Hairstyle Orange",
			"Irin's Hairstyle",
			"Irin's Jacket",
			"Irin's Pixie Wings",
			"Irin's Red Pixie Wings",
			"Irin's Red Succulent Hair Clips",
			"Irin's Rose Floral Pants",
			"Irin's Rose Jacket",
			"Irin's Succulent Hair Clips",
			"Magdalene's Apprentice Lamp",
			"Magdalene's Cape",
			"Magdalene's Dark Shoes",
			"Magdalene's Dim Apprentice Lamp",
			"Magdalene's Robes",
			"Magdalene's Shoes",
			"Magdalene's Sleeves",
			"Magdalene's Teal Cape",
			"Magdalene's Teal Robes",
			"Magdalene's Teal Sleeves",
			"Mycel's Glowshroom Circle",
			"Mycel's Hairstyle Lavender",
			"Mycel's Hairstyle",
			"Mycel's Head Fungi",
			"Mycel's Herbal Pouch",
			"Mycel's Lavender Suspicion",
			"Mycel's Lip",
			"Mycel's Mauve Swamp Dress",
			"Mycel's Mycology Basket",
			"Mycel's Pale Lip",
			"Mycel's Potion Swirls",
			"Mycel's Silver Potion Swirls",
			"Mycel's Staff",
			"Mycel's Suspicion",
			"Mycel's Swamp Dress",
			"Mycel's White Glowshroom Circle",
			"Mycel's White Head Fungi",
			"Mycel's White Herbal Pouch",
			"Mycel's White Jewel Staff",
			"Mycel's White Mycology Basket",
			"Trout's Ankle Sparks",
			"Trout's Blue Ankle Sparks",
			"Trout's Blue Hairstyle",
			"Trout's Blue Jacket",
			"Trout's Blue Shoes",
			"Trout's Blue Spark",
			"Trout's Hairstyle",
			"Trout's Jacket",
			"Trout's Pink Puffy Shorts",
			"Trout's Puffy Shorts",
			"Trout's Shoes",
			"Trout's Spark",
		],
		"town_sm": [
			"Cairn's Ceremonial Shorts",
			"Cairn's Corset",
			"Cairn's Dark Corset",
			"Cairn's Dark Pointy Shoes",
			"Cairn's Dark Segmented Tail",
			"Cairn's Mechanical Jacket",
			"Cairn's Mechanical Mask",
			"Cairn's Pointy Shoes",
			"Cairn's Red Ceremonial Shorts",
			"Cairn's Red Mechanical Jacket",
			"Cairn's Red Mechanical Mask",
			"Cairn's Segmented Tail",
			"Idra's Amethyst Dress",
			"Idra's Amethyst Hairstyle",
			"Idra's Amethyst Heels",
			"Idra's Amethyst Reminiscence",
			"Idra's Amethyst Wings",
			"Idra's Crystal Hairstyle",
			"Idra's Crystal Necklace",
			"Idra's Geode Skin",
			"Idra's Head Crystals",
			"Idra's Lips",
			"Idra's Pink Crystal Necklace",
			"Idra's Pink Lips",
			"Idra's Rosy Geode Skin",
			"Idra's Rosy Head Crystals",
			"Idra's Sapphire Dress",
			"Idra's Sapphire Heels",
			"Idra's Sapphire Reminiscence",
			"Idra's Sapphire Wings",
			"Marvel's Blue Teeth",
			"Marvel's Bright Crystal Pickaxe",
			"Marvel's Bronze Miner Overalls",
			"Marvel's Dark Mining Helm",
			"Marvel's Golden Crystal Pickaxe",
			"Marvel's Green Utility Jacket",
			"Marvel's Miner Overalls",
			"Marvel's Mining Helm",
			"Marvel's Stern Gaze",
			"Marvel's Stern Green Gaze",
			"Marvel's Teeth",
			"Marvel's Tousled Hairstyle",
			"Marvel's Tousled Red Hairstyle",
			"Marvel's Utility Jacket",
			"Nigel's Blue Bravery",
			"Nigel's Bravery",
			"Nigel's Ear Helmet",
			"Nigel's Fancy Armour",
			"Nigel's Fancy Steel Armour",
			"Nigel's Fancy Steel Sword",
			"Nigel's Fancy Sword",
			"Nigel's Lips",
			"Nigel's Puffy Purple Tail",
			"Nigel's Puffy Tail",
			"Nigel's Smiling Lips",
			"Nigel's Steel Ear Helmet",
			"Pascal's Buckled Shoes",
			"Pascal's Cave Hat",
			"Pascal's Dark Buckled Shoes",
			"Pascal's Green Hoarder Backpack",
			"Pascal's Green Miner Jacket",
			"Pascal's Green Ridged Shorts",
			"Pascal's Hoarder Backpack",
			"Pascal's Miner Jacket",
			"Pascal's Ridged Shorts",
			"Pascal's Short Mop Hairstyle Silver",
			"Pascal's Short Mop Hairstyle",
			"Pascal's Turquoise Cave Hat",
			"Thomas Replica",
			"Worn Thomas Replica",
			"Visindy's Chiffon Robes",
			"Visindy's Dreaming Eyes",
			"Visindy's Emerald Boots",
			"Visindy's Emerald Chiffon Robes",
			"Visindy's Emerald Dreaming Eyes",
			"Visindy's Emerald Hair Spikes",
			"Visindy's Emerald Lips",
			"Visindy's Emerald Scarf",
			"Visindy's Emerald Stalagmites",
			"Visindy's Hair Spikes",
			"Visindy's Lips",
			"Visindy's Silver Skin",
			"Visindy's Skin",
			"Visindy's Stalagmites",
			"Visindy's Swirling Hair",
			"Visindy's Swirling Silver Hair",
			"Visindy's Topaz Boots",
			"Visindy's Topaz Scarf",
		],
		"town_ac": [
			"Astra's Back Feathers",
			"Astra's Cerise Back Feathers",
			"Astra's Cerise Ear Feathers",
			"Astra's Cerise Head Wings",
			"Astra's Constellation Dress",
			"Astra's Ear Feathers",
			"Astra's Harpy Wings",
			"Astra's Head Wings",
			"Astra's Lips",
			"Astra's Mauve Harpy Wings",
			"Astra's Red Constellation Dress",
			"Astra's Red Lips",
			"Astra's Red Talon Boots",
			"Astra's Singular Expression",
			"Astra's Singular Red Expression",
			"Astra's Talon Boots",
			"Astra's Wispy Hairstyle Burgundy",
			"Astra's Wispy Hairstyle",
			"Carneau's Brown Shoes",
			"Carneau's Brunette Pigeons",
			"Carneau's Captain Hat",
			"Carneau's Colonel Cape",
			"Carneau's Gold Sideburn Hairstyle",
			"Carneau's Gold Twirly Mustache",
			"Carneau's Gray Trim Trousers",
			"Carneau's Pigeons",
			"Carneau's Prized Silver Sword",
			"Carneau's Prized Sword",
			"Carneau's Ruffled Shirt",
			"Carneau's Shoes",
			"Carneau's Sideburn Hairstyle",
			"Carneau's Silver Captain Hat",
			"Carneau's Silver Colonel Cape",
			"Carneau's Stern Brown Eyes",
			"Carneau's Stern Eyes",
			"Carneau's Suede Ruffled Shirt",
			"Carneau's Trim Trousers",
			"Carneau's Twirly Mustache",
			"Celestine's Cool Discernment",
			"Celestine's Cool Wooden Discernment",
			"Celestine's Decorative Wings",
			"Celestine's Laced Antique Petticoat",
			"Celestine's Laced Antique Umbrella",
			"Celestine's Laced Pale Poncho",
			"Celestine's Laced Petticoat",
			"Celestine's Laced Poncho",
			"Celestine's Laced Umbrella",
			"Celestine's Lips",
			"Celestine's Luxurious Honey Waves Hair",
			"Celestine's Luxurious Waves Hair",
			"Celestine's Prim Ruffles",
			"Celestine's Prim Soft Ruffles",
			"Celestine's Soft Decorative Wings",
			"Celestine's Soft Knit Antique Sweater",
			"Celestine's Soft Knit Sweater",
			"Celestine's Soft Lips",
			"Celestine's Winged Antique Hat",
			"Celestine's Winged Hat",
			"Johaness' Dark Green Ponytail",
			"Johaness' Dark Medallion Vest",
			"Johaness' Dark Sailing Tunic",
			"Johaness' Dark Seaside Sunset Backdrop",
			"Johaness' Dark Seaward Scarf",
			"Johaness' Dark Ship Hat",
			"Johaness' Floppy Boots",
			"Johaness' Medallion Vest",
			"Johaness' Murky Suspender Shorts",
			"Johaness' Murky Trinket Belt",
			"Johaness' Ponytail",
			"Johaness' Sailing Tunic",
			"Johaness' Seaside Sunset Backdrop",
			"Johaness' Seaward Scarf",
			"Johaness' Ship Hat",
			"Johaness' Suspender Shorts",
			"Johaness' Swampy Floppy Boots",
			"Johaness' Trinket Belt",
			"Lief's Discerning Glance",
			"Lief's Discerning Green Glance",
			"Lief's Gloves",
			"Lief's Hanging Lights",
			"Lief's Lightbulbs",
			"Lief's Lips",
			"Lief's Mauve Gloves",
			"Lief's Mauve Wings And Legs",
			"Lief's Puffy Coat",
			"Lief's Puffy Green Ribbon Coat",
			"Lief's Rose Teal Hanging Lights",
			"Lief's Rosy Lightbulbs",
			"Lief's Rosy Lips",
			"Lief's Soft Bob Hairstyle Dusty Pink",
			"Lief's Soft Bob Hairstyle",
			"Lief's Wings And Legs",
			"Pellier's Aura",
			"Pellier's Belt Of Lights",
			"Pellier's Belt Of Red Lights",
			"Pellier's Dark Ears",
			"Pellier's Dark Tail",
			"Pellier's Ears",
			"Pellier's Fire Aura",
			"Pellier's Fluffy Legs",
			"Pellier's Fluffy Red Legs",
			"Pellier's Fluffy Red Vest",
			"Pellier's Fluffy Vest",
			"Pellier's Horn",
			"Pellier's Light Gloves",
			"Pellier's Red Light Gloves",
			"Pellier's Ruby Horn",
			"Pellier's Tail",
			],
		"town_vr": [
			"Clione's Blue Shell Earrings",
			"Clione's Blue Shell Garland",
			"Clione's Camisole",
			"Clione's Consideration",
			"Clione's Glowing Coral",
			"Clione's Growing Coral",
			"Clione's Hairstyle",
			"Clione's Lavender Lips",
			"Clione's Lilac Consideration",
			"Clione's Lilac Tail",
			"Clione's Lips",
			"Clione's Shell Earrings",
			"Clione's Shell Garland",
			"Clione's Tail",
			"Clione's Ultraviolet Camisole",
			"Clione's Ultraviolet Hairstyle",
			"Olievar's Fluorescent Hairstyle",
			"Olievar's Fluorescent Oxygen Helmet",
			"Olievar's Fluorescent Seaboots",
			"Olievar's Fluorescent Seagloves",
			"Olievar's Fluorescent Seanaut Suit",
			"Olievar's Fluorescent Skin",
			"Olievar's Hairstyle",
			"Olievar's Oxygen Helmet",
			"Olievar's Seaboots",
			"Olievar's Seagloves",
			"Olievar's Seanaut Suit",
			"Olievar's Skin",

			"Poe's Blue Coral Sleeve Coat",
			"Poe's Blue Layered Robes",
			"Poe's Blue Ponytail",
			"Poe's Blue Tail Fins",
			"Poe's Citizen Badge",
			"Poe's Cobalt Citizen Badge",
			"Poe's Cobalt Festival Mask",
			"Poe's Cobalt School Shoes",
			"Poe's Coral Sleeve Coat",
			"Poe's Festival Mask",
			"Poe's Layered Robes",
			"Poe's Ponytail",
			"Poe's School Shoes",
			"Poe's Tail Fins",
			"Pyrifera's Billow Sleeves",
			"Pyrifera's Burgundy Billow Sleeves",
			"Pyrifera's Hairstyle",
			"Pyrifera's Kelp Skirt",
			"Pyrifera's Medicine Bottles",
			"Pyrifera's Neck Ribbon",
			"Pyrifera's Portable Jar",
			"Pyrifera's Portable Red Jar",
			"Pyrifera's Red Hairstyle",
			"Pyrifera's Red Kelp Skirt",
			"Pyrifera's Red Medicine Bottles",
			"Pyrifera's Red Scaled Bodice",
			"Pyrifera's Ruddy Neck Ribbon",
			"Pyrifera's Ruddy Skin",
			"Pyrifera's Scaled Bodice",
			"Pyrifera's Skin",
			"Wras' Adorned Headfins",
			"Wras' Adorned Rainbow Headfins",
			"Wras' Belted Arm Guard",
			"Wras' Belted Golden Arm Guard",
			"Wras' Bright Golden Cane",
			"Wras' Buckled Brown Jeans",
			"Wras' Buckled Jeans",
			"Wras' Calculation",
			"Wras' Colourful Golden Hairstyle",
			"Wras' Colourful Hairstyle",
			"Wras' Dusk Pirate Rags",
			"Wras' Gold Pirate Boots",
			"Wras' Golden Cane",
			"Wras' Golden Teeth",
			"Wras' Piercing Calculation",
			"Wras' Pirate Boots",
			"Wras' Pirate Rags",
			"Wras' Spiny Dusk Fins",
			"Wras' Spiny Fins",
			"Wras' Teeth",
			"Xarion's Crown",
			"Xarion's Current Swept Hair",
			"Xarion's Dark Judgment",
			"Xarion's Dark Shark Tail",
			"Xarion's Dark Shark Teeth",
			"Xarion's Deep Ocean Skin",
			"Xarion's Electric Current Swept Hair",
			"Xarion's Judgment",
			"Xarion's Judicial Cape",
			"Xarion's Judicial Coat",
			"Xarion's Judicial Medallion",
			"Xarion's Platinum Crown",
			"Xarion's Shark Tail",
			"Xarion's Shark Teeth",
			"Xarion's Silver Judicial Cape",
			"Xarion's Silver Judicial Coat",
			"Xarion's Silver Judicial Medallion",
			"Xarion's Silver Wrist Amulet",
			"Xarion's Skin",
			"Xarion's Wrist Amulet",
		],
		"nico": [
			"Beige Mid Length Skirt",
			"Beige Mini Skirt",
			"Black Ankle Socks",
			"Black Arm And Leg Belts",
			"Black Basic Shirt",
			"Black Bowtie",
			"Black Hair Ribbon",
			"Black Half Gloves",
			"Black Leather Gloves",
			"Black Mid Length Skirt",
			"Black Mini Skirt",
			"Black Pinstripe Leggings",
			"Black Stockings",
			"Black Suspenders",
			"Black Tie",
			"Blue Hair Ribbon",
			"Blue Stone Pendant",
			"Brown Arm And Leg Belts",
			"Brown Basic Shirt",
			"Brown Leather Gloves",
			"Brown Neck Kerchief",
			"Brown Tie",
			"Chest Scars",
			"Dark Freckles",
			"Dark Pants",
			"Denim Pants",
			"Frayed Black Tank",
			"Frayed Gray Tank",
			"Frayed White Tank",
			"Gold Bead Bracelets",
			"Gold Hair Ribbon",
			"Gold Single Bead Necklace",
			"Gold Spiked Bracelet",
			"Gold Stone Pendant",
			"Gray Ankle Socks",
			"Gray Half Gloves",
			"Gray Leather Gloves",
			"Gray Mini Skirt",
			"Gray Pants",
			"Gray Pinstripe Leggings",
			"Gray Stockings",
			"Green Hair Ribbon",
			"Green Stone Pendant",
			"Gunmetal Choker",
			"Gunmetal Single Bead Necklace",
			"Head Scars",
			"Ink Rose Tattoo",
			"Khaki Basic Shirt",
			"Leather Belt",
			"Leather Suspenders",
			"Leg Scars",
			"Light Freckles",
			"Loose Gold Tank",
			"Loose Leather Tank",
			"Loose Olive Tank",
			"Navy Bowtie",
			"Navy Mid Length Skirt",
			"Newbie Bandage Shoes",
			"Newbie Bandage Trousers",
			"Newbie High Waisted Shorts",
			"Newbie Leather Boots",
			"Newbie Leather Tank",
			"Newbie Puffy Shorts",
			"Newbie Puffy Sleeve Top",
			"Newbie Stitched Tunic",
			"Newbie Toeless Socks",
			"Onyx Bead Bracelets",
			"Onyx Spiked Bracelet",
			"Red Bowtie",
			"Red Hair Ribbon",
			"Red Neck Kerchief",
			"Red Rose Tattoo",
			"Red Stone Pendant",
			"Rolled Gray Socks",
			"Rolled White Socks",
			"Sailor Neck Kerchief",
			"Silver Bead Bracelets",
			"Silver Choker",
			"Silver Single Bead Necklace",
			"Silver Spiked Bracelet",
			"Small Hoop Earrings",
			"Spike Tattoo",
			"White Ankle Socks",
			"White Bowtie",
			"White Hair Ribbon",
			"White Half Gloves",
			"White Leather Gloves",
			"White Pinstripe Leggings",
			"White Stockings",
			"White Suspenders",
			"White Tie",
			"Yellow Neck Kerchief",
		],
		"new_nico": [
			"Basic Closed Eyes",
			"Basic Ebony Brown Skin",
			"Basic Grin",
			"Basic Happy Eyes",
			"Basic Laugh",
			"Basic Light Peach Skin",
			"Basic Lilac Skin",
			"Basic Rosey Brown Skin",
			"Basic Smile",
			"Basic Swamp Green Skin",
			"Beige Lace Shoes",
			"Black Lace Shoes",
			"Black Librarian Glasses",
			"Black Rose Patch",
			"Black Secretary Glasses",
			"Black Thick Wool Socks",
			"Body Stitches",
			"Brown Lace Shoes",
			"Brown Thick Wool Socks",
			"Brown Trousers",
			"Gold Drop Earrings",
			"Gold Ear Cuff",
			"Gold Hoop Earrings",
			"Gold Monocle",
			"Golden Librarian Glasses",
			"Golden Secretary Glasses",
			"Golden Sparkles",
			"Gray Thick Wool Socks",
			"Grey Trousers",
			"Navy Trousers",
			"Onyx Drop Earrings",
			"Onyx Ear Cuff",
			"Onyx Hoop Earrings",
			"Onyx Monocle",
			"Red Rose Patch",
			"Silver Drop Earrings",
			"Silver Ear Cuff",
			"Silver Hoop Earrings",
			"Silver Librarian Glasses",
			"Silver Monocle",
			"Silver Secretary Glasses",
			"White Sparkles",
		],
		"deity": [
			"Ingi Deity",
			"Ingi's Fiery Skin",
			"Ingi's Tattered Robes",
			"Ivita's Mask",
			"Ombra Spirit",
			"Ombra's Cloak",
			"Ombra's Forest",
			"Pann Deity",
			"Parsnip On A Stick",
			"Soll Coat",
			"Soll's Locks",
			"Thalies' Antlers",
			"Thalies' Emblem",
			"Turara Deity",
			"Vaer's Symbols",
			"Vaer's Tights",
			"Ravan's Mask",
			"Ravan's Tomes",
			"Ravan's Winged Capelet",
			"Kelbi's Likeness",
			"Kelbi's Staff",
			"Signi's Boots",
			"Signi's Tears",
			"Aeolin's Wings",
		],
		"alch": [
			"Blue Egg Friends",
			"Blue Egg Nest",
			"Blue Snail Friends",
			"Blue Snail Helm",
			"Egg Friends",
			"Egg Nest",
			"Gold Shark Friend",
			"Gold Shark Plush",
			"Pink Egg Friends",
			"Pink Egg Nest",
			"Pink Snail Friends",
			"Pink Snail Helm",
			"Shadow Shark Friend",
			"Shadow Shark Plush",
			"Shark Friend",
			"Shark Plush",
			"Snail Friends",
			"Snail Helm",
		],
		"referral": [
			"Black Royal Cloak",
			"Black Royal Crown",
			"Black Royal Sceptor",
			"Blue Royal Cloak",
			"Blue Royal Crown",
			"Blue Royal Sceptor",
			"Red Royal Cloak",
			"Red Royal Crown",
			"Red Royal Sceptor",
		],
		"event": [
			"Autumn Bandages",
			"Autumn Beard",
			"Autumn Belt",
			"Autumn Forest Mushrooms",
			"Autumn Long Scarf",
			"Autumn Mane Hair",
			"Autumn Ponytail",
			"Autumn Rags",
			"Autumn Shirt",
			"Autumn Witch Hat",
			"Mountain Cloak",
			"Prismatic Fields Backdrop",
			"Prismatic Star Gem",
			"Proud Snail Friends",
			"Spring Bloom",
			"Summer Fairy Wings",
			"Summer Leaf Belt",
			"Summer Long Hair",
			"Summer Picnic Basket",
			"Summer Sandals",
			"Summer Short Hair",
			"Summer Sun Hat",
			"Summer Tied Shirt",
			"Summer Toga",
			"Summer Wild Flowers",
			"Unsuspicious Puddle",
			"Winter Bell Coat",
			"Winter Bowtied Boots",
			"Winter Braids",
			"Winter Fox",
			"Winter Hair Ornament",
			"Winter Owlets",
			"Winter Ribbon Sweater",
			"Winter Scarf",
			"Winter Short Hair",
			"Winter Snowman",
			"Winter Suspender Pants",
			"Winter Worker's Boots",
		],
		"adventuring": [
			"Louise Hill Produce",
			"3s Forest Gate",
			"Silvies Mine Lamps",
			"Aviar Air Courier Suit",
			"Vaer Reef Kelp Garden",
			"Charming Capelet",
			"Charming Hill Rabbit",
			"Charming Sea Serpent",
			"Charming Single Horn",
			"Charming Wings",
			"Comprehensive Capelet",
			"Comprehensive Hill Rabbit",
			"Comprehensive Sea Serpent",
			"Comprehensive Single Horn",
			"Comprehensive Wings",
			"Honourable Capelet",
			"Honourable Hill Rabbit",
			"Honourable Sea Serpent",
			"Honourable Single Horn",
			"Honourable Wings",
			"Tenacious Capelet",
			"Tenacious Hill Rabbit",
			"Tenacious Sea Serpent",
			"Tenacious Single Horn",
			"Tenacious Wings",
			"Prismatic Capelet",
			"Prismatic Hill Rabbit",
			"Prismatic Sea Serpent",
			"Prismatic Single Horn",
			"Prismatic Wings",
		],
		"affection": [
			"Black Heart Chest Plate",
			"Black Heart Greaves",
			"Black Heart Head Piece",
			"Black Heart Lightning Chest Plate",
			"Black Heart Lightning Greaves",
			"Black Heart Lightning Head Piece",
			"Broken Hearts",
			"Cold Heart Bandana",
			"Cold Heart Hat",
			"Cold Heart Jacket",
			"Cold Heart Lightning Bandana",
			"Cold Heart Lightning Hat",
			"Cold Heart Lightning Jacket",
			"Cold Heart Lightning Long Skirt",
			"Cold Heart Lightning Pike",
			"Cold Heart Lightning Trousers",
			"Cold Heart Long Skirt",
			"Cold Heart Pike",
			"Cold Heart Trousers",
			"Lovely Hearts",
			"Ornate Horns Of Loyalty",
			"Red Heart Chest Plate",
			"Red Heart Greaves",
			"Red Heart Head Piece",
			"Red Heart Shining Chest Plate",
			"Red Heart Shining Greaves",
			"Red Heart Shining Head Piece",
			"Silken Brocade Of Loyalty",
			"Silken Wingsuit Of Loyalty",
			"Warm Heart Blouse",
			"Warm Heart Bouquet",
			"Warm Heart Hat",
			"Warm Heart Scarf",
			"Warm Heart Shining Blouse",
			"Warm Heart Shining Bouquet",
			"Warm Heart Shining Hat",
			"Warm Heart Shining Scarf",
			"Warm Heart Shining Skirt",
			"Warm Heart Shining Trousers",
			"Warm Heart Skirt",
			"Warm Heart Trousers",
		],
		"animal": [
			"Animal Black Cat Ears",
			"Animal Brown Bird Crown",
			"Animal Brown Bird Tail",
			"Animal Brown Goat Ears",
			"Animal Brown Goat Tail",
			"Animal Brown Rabbit Ears",
			"Animal Bunny Tail",
			"Animal Cat Tail",
			"Animal Curly Short Bob Black",
			"Animal Curly Short Bob Gray",
			"Animal Curly Short Bob Honey",
			"Animal Deer Ears",
			"Animal Deer Tail",
			"Animal Fish Fins",
			"Animal Fish Tail",
			"Animal Puffcurl Hair Black",
			"Animal Puffcurl Hair Chestnut",
			"Animal Puffcurl Hair Pink",
			"Animal Red Wolf Ears",
			"Animal Short Hair Chestnut",
			"Animal Short Hair Cream",
			"Animal Short Hair Pink",
			"Animal Skin Contrast",
			"Animal Skin Dark Stripes",
			"Animal Skin Feathery",
			"Animal Skin Light Stripes",
			"Animal Skin Mottled",
			"Animal Wavy Long Hair Black",
			"Animal Wavy Long Hair Honey",
			"Animal Wavy Long Hair Pink",
			"Animal Wolf Tail",
			"Basic Brown Animal Eyes",
			"Basic Golden Animal Eyes",
			"Basic Red Animal Eyes",
			"Cheerful Animal Mouth",
			"Fancy Animal Eyes Doe",
			"Fancy Animal Eyes Goat",
			"Fancy Animal Eyes Reptile",
			"Pouting Animal Mouth",
		],
		"elf": [
			"Elven Blue Gem Bracelets",
			"Elven Blue Gem Rune",
			"Elven Green Gem Circlet",
			"Elven Green Gem Rune",
			"Elven Long Braid Blonde",
			"Elven Long Braid Brown",
			"Elven Long Braid Silver",
			"Elven Pink Gem Choker",
			"Elven Pink Gem Rune",
			"Elven Puffcurl Hair Cream",
			"Elven Puffcurl Hair Green",
			"Elven Puffcurl Hair Grey",
			"Elven Purple Gem Fascinator",
			"Elven Purple Gem Rune",
			"Elven Red Gem Belt",
			"Elven Red Gem Rune",
			"Elven Short Hair Blonde",
			"Elven Short Hair Brown",
			"Elven Short Hair Gray",
			"Elven Side Braid Honey",
			"Elven Side Braid Red",
			"Elven Side Braid Silver",
			"Elven Skin Forest",
			"Elven Skin Goldleaf",
			"Elven Skin Midnight",
			"Elven Skin Pale",
			"Elven Skin Wooden",
			"Elven Tied Hair Black",
			"Elven Tied Hair Blonde",
			"Elven Tied Hair Brown",
			"Elven White Gem Anklets",
			"Elven White Gem Rune",
			"Elven Yellow Gem Necklace",
			"Elven Yellow Gem Rune",
			"Pensive Elven Mouth",
			"Pouting Elven Mouth",
			"Shining Elven Eyes Blue",
			"Shining Elven Eyes Gold",
			"Shining Elven Eyes Green",
			"Sleepy Elven Eyes Blue",
			"Sleepy Elven Eyes Green",
			"Sleepy Elven Eyes Red",
		],
		"galactic": [
			"Fanged Galactic Mouth",
			"Galactic Anklet Antenna",
			"Galactic Anklet Crest",
			"Galactic Arc Burst Antenna",
			"Galactic Arc Burst Crest",
			"Galactic Broken Halo Antenna",
			"Galactic Broken Halo Crest",
			"Galactic Cloud Bob Blue",
			"Galactic Cloud Bob Magenta",
			"Galactic Cloud Bob Silver",
			"Galactic Cracked Wing Antenna",
			"Galactic Cracked Wing Crest",
			"Galactic Long Curls Blue",
			"Galactic Long Curls Magenta",
			"Galactic Long Curls Silver",
			"Galactic Puffcurl Hair Night",
			"Galactic Puffcurl Hair Peach",
			"Galactic Puffcurl Hair Sky",
			"Galactic Ring Antenna",
			"Galactic Ring Crest",
			"Galactic Short Hair Blue",
			"Galactic Short Hair Grey",
			"Galactic Short Hair Peach",
			"Galactic Skin Dawn",
			"Galactic Skin Midnight",
			"Galactic Skin Nebula",
			"Galactic Skin Nova",
			"Galactic Skin Storm",
			"Galactic Tiara Antenna",
			"Galactic Tiara Crest",
			"Galactic Trident Antenna",
			"Galactic Trident Crest",
			"Lucid Galactic Eyes Emerald",
			"Lucid Galactic Eyes Ruby",
			"Lucid Galactic Eyes Sapphire",
			"Lucid Galactic Eyes Silver",
			"Limpid Galactic Eyes Blue",
			"Limpid Galactic Eyes Midnight",
			"Limpid Galactic Eyes Red",
			"Toothy Galactic Mouth",
		],
		"human": [
			"Clear Blue Human Eyes",
			"Clear Brown Human Eyes",
			"Clear Green Human Eyes",
			"Human Cheerful Bob Blonde",
			"Human Cheerful Bob Brown",
			"Human Cheerful Bob Umber",
			"Human Cosmos Auro",
			"Human Cosmos Chestpiece",
			"Human Cowlick Hair Blonde",
			"Human Cowlick Hair Brown",
			"Human Cowlick Hair Red",
			"Human Fire Auro",
			"Human Fire Knee Guard",
			"Human Ink Auro",
			"Human Ink Sash",
			"Human Leaf Auro",
			"Human Leaf Chestplate",
			"Human Light Auro",
			"Human Light Halfhelm",
			"Human Long Hair Black",
			"Human Long Hair Dusty Pink",
			"Human Long Hair Honey Brown",
			"Human Puffcurl Hair Ginger",
			"Human Puffcurl Hair Gold",
			"Human Puffcurl Hair Mahogany",
			"Human Short Hair Almond",
			"Human Short Hair Black",
			"Human Short Hair Gold",
			"Human Skin Dark",
			"Human Skin Deep",
			"Human Skin Pale",
			"Human Skin Reddened",
			"Human Skin Tan Freckled",
			"Human Water Auro",
			"Human Water Sabaton",
			"Human Wind Auro",
			"Human Wind Belt",
			"Smiling Human Mouth",
			"Pouting Human Mouth",
			"Taciturn Gold Human Eyes",
			"Taciturn Gray Human Eyes",
			"Taciturn Red Human Eyes",
		],
		"oran": [
			"Circus Unicorn Baton",
			"Circus Unicorn Blouse",
			"Circus Unicorn Hooves",
			"Circus Unicorn Lips",
			"Circus Unicorn Mohawk",
			"Circus Unicorn Ruffles",
			"Circus Unicorn Tail",
			"Circus Unicorn's Horn",
			"Eclipsed Seraph Attack",
			"Eclipsed Seraph Chains",
			"Eclipsed Seraph Gloves",
			"Eclipsed Seraph Jacket",
			"Eclipsed Seraph Knee Guards",
			"Eclipsed Seraph Short Hair",
			"Eclipsed Seraph Tights",
			"Eclipsed Seraph Wing Mask",
			"Leviathan Boots",
			"Leviathan Claws",
			"Leviathan Diadem",
			"Leviathan Lips",
			"Leviathan Mesmer",
			"Leviathan Necklace",
			"Masked Wanderer Head Scarf",
			"Masked Wanderer Lantern",
			"Masked Wanderer Lion Mask",
			"Masked Wanderer Owl Mask",
			"Masked Wanderer Reverie",
			"Masked Wanderer Shawl",
			"Masked Wanderer Short Hair",
			"Masked Wanderer Swirling Smoke",
			"Mothlike Crest",
			"Mothlike Fangs",
			"Mothlike Feathered Feet",
			"Mothlike Stained Claws",
			"Mothlike Third Eye",
			"Mothlike Tied Feeler Hairstyle",
			"Rosethorn Blue Rose Tights",
			"Rosethorn Discs",
			"Rosethorn Lips",
			"Rosethorn Short Hairstyle",
			"Rosethorn Sweeping Drapes",
			"Rosethorn Vine Boots",
			"Winter Scholar Blouse",
			"Winter Scholar Boa",
			"Winter Scholar Boots",
			"Winter Scholar Short Hair",
			"Winter Scholar Skin",
			"Winter Scholar Songbird",
			"Winter Scholar's Glacier",
			"Winter Scholar's Perception",
			"Butterfly Mystic Anklets",
			"Butterfly Mystic Boots",
			"Butterfly Mystic Braid",
			"Butterfly Mystic Crop Shirt",
			"Butterfly Mystic Face Wings",
			"Butterfly Mystic Hairpin",
			"Butterfly Mystic Pants",
			"Butterfly Mystic Winglets",
			"Cosmic Mage Frilled Robes",
			"Cosmic Mage Moon",
			"Cosmic Mage Short Hair",
			"Cosmic Mage Skin",
			"Cosmic Mage Skin Crystals",
			"Cosmic Mage Vision",
			"Elder Forest Bone Belt",
			"Elder Forest Curls",
			"Elder Forest Eye Mask",
			"Elder Forest Mantle",
			"Elder Forest Skin",
			"Elder Forest Straw Cape",
			"Elder Forest Tights",
			"Elder Forest Wisdom",
			"Orchard Historian Earrings",
			"Orchard Historian Floral Hat",
			"Orchard Historian Knotted Drapes",
			"Orchard Historian Knotted Shift",
			"Orchard Historian Mantled Sleeves",
			"Orchard Historian Reminiscence",
			"Orchard Historian Sword",
			"Orchard Historian Tousled Short Hair",
		],
		"pai": [
			"Circus Unicorn Backdrop",
			"Circus Unicorn Overalls",
			"Circus Unicorn Pigtails",
			"Circus Unicorn Pony",
			"Circus Unicorn Rose Border",
			"Circus Unicorn Skin",
			"Circus Unicorn Tutu",
			"Circus Unicorn's Trust",
			"Eclipsed Seraph Abyss",
			"Eclipsed Seraph Braids",
			"Eclipsed Seraph Gaze",
			"Eclipsed Seraph Halo",
			"Eclipsed Seraph Pauldrons",
			"Eclipsed Seraph Skin",
			"Eclipsed Seraph Sword",
			"Eclipsed Seraph Wings",
			"Leviathan Gradated Hair",
			"Leviathan Greaves",
			"Leviathan Tail",
			"Leviathan Tied Hair",
			"Leviathan Top",
			"Leviathan Trident",
			"Masked Wanderer Body Paint",
			"Masked Wanderer Coat",
			"Masked Wanderer Deer Legs",
			"Masked Wanderer Deer Mask",
			"Masked Wanderer Dragon Mask",
			"Masked Wanderer Dragon",
			"Masked Wanderer Long Hair",
			"Masked Wanderer Saber Mask",
			"Moth Familiars",
			"Mothlike Long Feeler Hairstyle",
			"Mothlike Puffy Tights",
			"Mothlike Single Iris Gaze",
			"Mothlike Winged Coat",
			"Mothlike Wings",
			"Rosethorn Backdrop",
			"Rosethorn Decora Skin",
			"Rosethorn Floral Horns",
			"Rosethorn Long Forest Hairstyle",
			"Rosethorn Perception",
			"Rosethorn Petal Cloak",
			"Winter Scholar Cloak",
			"Winter Scholar Dress Robes",
			"Winter Scholar Fortress",
			"Winter Scholar Hood",
			"Winter Scholar Mountain Calf",
			"Winter Scholar Snow Globe",
			"Winter Scholar Tied Hair",
			"Winter Scholar's Flurries",
			"Butterfly Mystic Backdrop",
			"Butterfly Mystic Chiffon Dress",
			"Butterfly Mystic Lamp",
			"Butterfly Mystic Long Hair",
			"Butterfly Mystic Skin",
			"Butterfly Mystic Veil",
			"Butterfly Mystic Wings",
			"Butterfly Mystic's Regard",
			"Cosmic Mage Black Cat",
			"Cosmic Mage Flight",
			"Cosmic Mage Hat",
			"Cosmic Mage Long Hair",
			"Cosmic Mage Moon Staff",
			"Cosmic Mage Seeing Pearl",
			"Cosmic Mage Tapestry",
			"Cosmic Mage White Cat",
			"Elder Forest Beast Legs",
			"Elder Forest Overgrowth",
			"Elder Forest Patterned Dress",
			"Elder Forest Patterned Trousers",
			"Elder Forest Skull Hood",
			"Elder Forest Skull Mask",
			"Elder Forest Veil Crown",
			"Elder Forest Vined Feet",
			"Orchard Historian Buttoned Smock",
			"Orchard Historian Floral Wallpaper",
			"Orchard Historian Florid Body Paint",
			"Orchard Historian Petal Headdress",
			"Orchard Historian Pleated Coat",
			"Orchard Historian Silk Robe",
			"Orchard Historian Tied Long Hair",
			"Orchard Historian Veiled Sun Hat",
		],
	};
	var extra_aff = {
		"town_lh": [
			"Bearnard's Turnip Stew",
			"Buli's Scientific Equipment",
			"Calbet's Picnic Basket",
			"Fantasia's Desert Hood",
			"Lilia's Battle Dress",
			"Not A Wizard Beard",
		],
		"town_3f": [
			"Barclay's Reading Spot",
			"Glume's Rose Vines",
			"Irin's Forest Sprites",
			"Magdalene's Skin",
			"Mycel's Forest Fox",
			"Trout's Mr Turnip Helmet",
		],
		"town_sm": [
			"Cairn's Music Player",
			"Idra's Flower Basket",
			"Marvel's Breakfast Table",
			"Nigel's Cool Cape",
			"Pascal's Spelunking Gear",
			"Visindy's Worm Terrarium",
		],
		"town_ac": [
			"Astra's Golden Telescope",
			"Carneau's Old Courier Bag",
			"Celestine's Blue Essence Rings",
			"Johaness' Bell Staff",
			"Lief's Lightbulb Crown",
			"Pellier's Bookshelf",
		],
		"town_vr": [
		],
	};
	var extra_alch = {
		"town_lh": [
			"Bearnard's Golden Broom",
			"Bearnard's Red Farming Gloves",
			"Bearnard's Red Farming Overalls",
			"Bearnard's Red Farming Shoes",
			"Bearnard's Red Ribbon Sun Hat",
			"Bearnard's Yellow Farming Shirt",
			"Buli's Golden Essence Rings",
			"Buli's Golden Essence Spirit",
			"Buli's Hairstyle Pink",
			"Buli's Magic Golden Pots",
			"Buli's Mysterious Golden Dress",
			"Calbet's Cloud Armour",
			"Calbet's Cloud Training Quiver",
			"Calbet's Hairstyle Clouds",
			"Calbet's Silver Training Bow",
			"Calbet's Sky Archery Boots",
			"Calbet's Sky Cabbage Friend",
			"Calbet's Sky Pantaloons",
			"Fantasia's Dusk Dagger Gloves",
			"Fantasia's Dusk Desert Halo",
			"Fantasia's Dusk Fox Tail",
			"Fantasia's Dusk Rogue Boots",
			"Fantasia's Dusk Training Shirt",
			"Fantasia's Hairstyle Dusk",
			"Fantasia's Warm Eyepatch",
			"Lilia's Golden Battle Tiara",
			"Lilia's Golden Flower Gem Necklace",
			"Lilia's Golden Gauntlets",
			"Lilia's Golden Hairstyle",
			"Lilia's Golden Soldier Leggings",
			"Lilia's Golden Training Armor",
			"Lilia's Golden Training Lances",
			"Not A Wizard Gold Hat",
			"Not A Wizard Gold Robe Drapings",
			"Not A Wizard Gold Robe Top",
			"Not A Wizard Hairstyle Gold",
			"Not A Wizard Magic Wand",
			"Not A Wizard Magical Trinket",
			"Not Wizard Blue Keys",
		],
		"town_3f": [
			"Barclay's Black Belts",
			"Barclay's Blue Flower Mantle",
			"Barclay's Blue Flower Puppet",
			"Barclay's Blue Garland",
			"Barclay's Blue Indignance",
			"Barclay's Hairstyle Midnight",
			"Barclay's Midnight Lip",
			"Barclay's Midnight Sweater",
			"Barclay's Midnight Trousers",
			"Barclay's Ragged Midnight Cape",
			"Glume's Black Lip",
			"Glume's Black Rose Eyepatch",
			"Glume's Black Vine Chain",
			"Glume's Blue Vine Shoes",
			"Glume's Dark Thorn Pouch",
			"Glume's Hairstyle Ice Ombre",
			"Glume's Pastel Lace Headdress",
			"Glume's Stark Ferocity",
			"Glume's Striped Bone Dress",
			"Glume's Striped Loop Scarf",
			"Irin's Blue Pixie Wings",
			"Irin's Blue Rose Jacket",
			"Irin's Blue Succulent Hair Clips",
			"Irin's Hairstyle Green",
			"Irin's Floral Pants",
			"Magdalene's Golden Cape",
			"Magdalene's Golden Robes",
			"Magdalene's Golden Shoes",
			"Magdalene's Golden Sleeves",
			"Magdalene's Pixie Apprentice Lamp",
			"Mycel's Dreamy Potion Swirls",
			"Mycel's Dreamy Swamp Dress",
			"Mycel's Pastel Glowshroom Circle",
			"Mycel's Pastel Hairstyle",
			"Mycel's Pastel Head Fungi",
			"Mycel's Pastel Lip",
			"Mycel's Pastel Mycology Basket",
			"Mycel's Pastel Staff",
			"Mycel's Pastel Suspicion",
			"Mycel's Pink Herbal Pouch",
			"Trout's Orange Ankle Sparks",
			"Trout's Orange Spark",
			"Trout's Pumpkin Hairstyle",
			"Trout's Pumpkin Jacket",
			"Trout's Pumpkin Puffy Shorts",
			"Trout's Pumpkin Shoes",
		],
		"town_sm": [
			"Cairn's Ceremonial Moonstone Shorts",
			"Cairn's Mechanical Moonstone Jacket",
			"Cairn's Mechanical Moonstone Mask",
			"Cairn's Gray Corset",
			"Cairn's Pointy Silver Shoes",
			"Cairn's Segmented Silver Tail",
			"Idra's Gold Crystal Necklace",
			"Idra's Gold Geode Skin",
			"Idra's Gold Head Crystals",
			"Idra's Gold Lips",
			"Idra's Gold Wings",
			"Idra's Golden Dress",
			"Idra's Golden Hairstyle",
			"Idra's Golden Reminiscence",
			"Idra's Shattered Gold Heels",
			"Nigel's Golden Bravery",
			"Nigel's Golden Ear Helmet",
			"Nigel's Fancy Gold Armour",
			"Nigel's Fancy Gold Sword",
			"Nigel's Puffy Gold Tail",
			"Nigel's Toothy Smile",
			"Marvel's Bronze Mining Helm",
			"Marvel's Crystal Pickaxe",
			"Marvel's Red Miner Overalls",
			"Marvel's Red Utility Jacket",
			"Marvel's Stern Blue Gaze",
			"Marvel's Tousled Blonde Hairstyle",
			"Marvel's Yellow Teeth",			
			"Pascal's Buckled Fire Shoes",
			"Pascal's Fiery Miner Jacket",
			"Pascal's Fiery Short Mop Hairstyle",
			"Pascal's Gold Hoarder Backpack",
			"Pascal's Golden Ridged Shorts",
			"Pascal's Red Cave Hat",
			"Fancy Thomas Replica",
			"Visindy's Artifact Skin",
			"Visindy's Dreaming Mirage Eyes",
			"Visindy's Mirage Boots",
			"Visindy's Mirage Hair Spikes",
			"Visindy's Mirage Scarf",
			"Visindy's Mirage Stalagmites",
			"Visindy's Pearlescent Chiffon Robes",
			"Visindy's Rose Lips",
			"Visindy's Swirling Mirage Hair",
		],
		"town_ac": [
			"Astra's Bronze Back Feathers",
			"Astra's Bronze Talon Boots",
			"Astra's Cream Constellation Dress",
			"Astra's Cream Ear Feathers",
			"Astra's Gold Head Wings",
			"Astra's Pale Lips",
			"Astra's Singular Pale Expression",
			"Astra's White Harpy Wings",
			"Astra's Wispy White Hairstyle",
			"Carneau's Gold Colonel Cape",
			"Carneau's Gold Lined Ruffled Shirt",
			"Carneau's Gold Trim Captain Hat",
			"Carneau's Golden Shoes",
			"Carneau's Gray Twirly Mustache",
			"Carneau's Prized Goldrush Sword",
			"Carneau's Silver Gold Trim Trousers",
			"Carneau's Silver Sideburn Hairstyle",
			"Carneau's Stern Golden Eyes",
			"Carneau's Striped Pigeons",
			"Celestine's Cool Pale Discernment",
			"Celestine's Decorative Pale Wings",
			"Celestine's Gothic Lips",
			"Celestine's Laced Gothic Petticoat",
			"Celestine's Laced Gothic Umbrella",
			"Celestine's Luxurious Midnight Waves Hair",
			"Celestine's Prim Pale Ruffles",
			"Celestine's Soft Knit White Sweater",
			"Celestine's Striped Laced Poncho",
			"Celestine's Winged Gothic Hat",
			"Johaness' Bright Floppy Boots",
			"Johaness' Bright Medallion Vest",
			"Johaness' Bronze Seaward Scarf",
			"Johaness' Gold Suspender Shorts",
			"Johaness' Pale Cream Ponytail",
			"Johaness' Pale Sailing Tunic",
			"Johaness' Seaside Lavish Sunset Backdrop",
			"Johaness' Silver Ship Hat",
			"Johaness' White Trinket Belt",
			"Lief's Discerning Golden Glance",
			"Lief's Golden Gloves",
			"Lief's Green Gold Hanging Lights",
			"Lief's Green Lightbulbs",
			"Lief's Green Lips",
			"Lief's Green Wings And Legs",
			"Lief's Puffy Golden Coat",
			"Lief's Soft Bob Hairstyle Gold",
			"Pellier's Belt Of Blue Lights",
			"Pellier's Blue Aura",
			"Pellier's Blue Light Gloves",
			"Pellier's Fluffy Golden Legs",
			"Pellier's Fluffy Golden Vest",
			"Pellier's Gold Horn",
			"Pellier's Golden Ears",
			"Pellier's Golden Tail",
		],
		"town_vr": [
			"Clione's Algae Coral",
			"Clione's Gold Shell Garland",
			"Clione's Golden Camisole",
			"Clione's Golden Consideration",
			"Clione's Golden Hairstyle",
			"Clione's Golden Lips",
			"Clione's Golden Tail",
			"Clione's Green Shell Earrings",
			"Olievar's Iridescent Hairstyle",
			"Olievar's Iridescent Oxygen Helmet",
			"Olievar's Iridescent Seaboots",
			"Olievar's Iridescent Seagloves",
			"Olievar's Iridescent Seanaut Suit",
			"Olievar's Iridescent Skin",
			"Poe's Opal Festival Mask",
			"Poe's Silver Citizen Badge",
			"Poe's Silver Coral Sleeve Coat",
			"Poe's Silver Ponytail",
			"Poe's Silver School Shoes",
			"Poe's Silver Tail Fins",
			"Poe's Silvery Layered Robes",
			"Pyrifera's Blue Billow Sleeves",
			"Pyrifera's Blue Kelp Skirt",
			"Pyrifera's Blue Scaled Bodice",
			"Pyrifera's Blue Skin",
			"Pyrifera's Glowing Blue Hairstyle",
			"Pyrifera's Glowing Medicine Bottles",
			"Pyrifera's Portable Glowing Jar",
			"Pyrifera's White Neck Ribbon",
			"Wras' Belted Blue Arm Guard",
			"Wras' Blue Pirate Rags",
			"Wras' Buckled Night Jeans",
			"Wras' Cold Calculation",
			"Wras' Highlighted Hairstyle",
			"Wras' Night Teeth",
			"Wras' Sapphire Cane",
			"Wras' Sapphire Pirate Boots",
			"Wras' Silver Adorned Headfins",
			"Wras' Spiny Blue Fins",
			"Xarion's Coal Skin",
			"Xarion's Red Current Swept Hair",
			"Xarion's Red Judgment",
			"Xarion's Red Judicial Cape",
			"Xarion's Red Judicial Coat",
			"Xarion's Red Shark Tail",
			"Xarion's Red Shark Teeth",
			"Xarion's Red Wrist Amulet",
			"Xarion's Ruby Crown",
			"Xarion's Ruby Judicial Medallion",
		],
	};
	var pickFrom;
};