#!/bin/perl -w
#
# https://adventofcode.com/2018/day/2
#
# This was surprisingly difficult for a day 2, particularly the second part. We struggled with how to approach it without
# pure brute force until someone suggested that regex could actually be used for it.

use strict;
use List::Util qw(any);

print "2018 Day 2\n\n";
my $puzzle = do { local $/; <DATA> }; # slurp it
my @ids = split "\n", $puzzle;

my $doubles = 0;
my $triples = 0;
foreach my $id (@ids) {
	# First, clump all repeated letters together and remove any groups > 3
	my $sorted = join('', sort split('', $id));
	$sorted =~ s/(\w)\1{3,}//g;
	# Now match & remove triples, then match doubles
	$triples++ if ($sorted =~ s/(\w)\1{2}//g);
	$doubles++ if ($sorted =~ /(\w)\1/);
}

print "P1: There were $doubles doubles and $triples triples, giving a checksum of ", ($triples*$doubles), "\n";

# regex madness. We can use the /s modifier to work on the entire input at once by ignoring the newlines and
# try to match (group)char(group) followed later by another one. We'll also want to prefix the whole thing with
# a non-greedy anything match and suffix it with a greddy one to isolate just the part we want. Finally, by
# using s///r and replacing (a copy of) the whole string with just the two matched groups, it returns exactly
# what the problem asked for - a string of the common letters with the one different letter removed.
my $match = $puzzle =~ s/.*?\b(\w*)\w(\w*)\b.*?\1\w\2.*/$1$2/sr;
print "\nP2: The common characters for the two near-exact IDs are $match.\n";

__DATA__
rvefnvyxzbodgpnpkumawhijsc
rvefqtyxzsddglnppumawhijsc
rvefqtywzbodglnkkubawhijsc
rvefqpyxzbozglnpkumawhiqsc
rvefqtyxzbotgenpkuyawhijsc
rvefqtyxzbodglnlkumtphijsc
rwefqtykzbodglnpkumawhijss
rvynqtyxzbodglnpkumawrijsc
rvefqtyxlbodgcnpkumawhijec
rvefqtyxzbodmlnpnumawhijsx
rvefqtyxzbqdbdnpkumawhijsc
rvefqtyxzlodblnpkuiawhijsc
rvefqtyizrodelnpkumawhijsc
rveffjyxzgodglnpkumawhijsc
rvefqjyxzbodalnpkumadhijsc
rvefqtidzbodglnpkumawhdjsc
hvefqtygzbodglnpkumawhijfc
rzefqtyxzbodglfhkumawhijsc
rmefqtyxzbolglnpkumaehijsc
rnefqqyxzbodglnhkumawhijsc
rvwfqvyxzbodglnpcumawhijsc
rvefqtyxzbokgltpkumavhijsc
rvefciyxzbodglnmkumawhijsc
rvefptyxzbodglnpkuhashijsc
rvefqtyxzrodglnpkxmawhiqsc
rvefqtyxzbotglnpkumawriwsc
rvufqtyxzbodglnplumawhijvc
rvefutykzbodglnpkumaahijsc
rvefqtyxqbodgllprumawhijsc
rvegqttxzbodgllpkumawhijsc
dvefqtyxzsodglnpkumawdijsc
rvefqtyxkbodglnfkumawhijsj
rvefqtyxzbodnlnpcumawhijnc
rvefqtyxzbodglfpkuocwhijsc
rvecqtyxzbbdganpkumawhijsc
rvefytyxzbodglnpkubgwhijsc
rvefxtyazbomglnpkumawhijsc
rvefqgyxzbodglnpkumawyiksc
avefqtyxzbodglnfkummwhijsc
fvefqtyxzbbdglnpkumswhijsc
rvefqtyxzxodglnpkumuuhijsc
rvezqtyxzbydclnpkumawhijsc
rvefqtyxzbohglnpkumawdijjc
rvejqtyxzbodrlnpkumawhijsd
rvefitzxzbxdglnpkumawhijsc
rvefutyxzbvdglnikumawhijsc
rvefqtyazbodgqnbkumawhijsc
rvefqtyxzbolglnpkwmajhijsc
rvefqtyxzjodglnpgwmawhijsc
rvefhtyxzbodglbpaumawhijsc
mvexqtyxzbodglnpkumawrijsc
rvefqtyxwbodglnpkumawhbxsc
rvefqtyxzbodgsnpkudawsijsc
rvwfqtyxzbonglnwkumawhijsc
rvefqtyxzjodglnpkfmawhwjsc
rvefqtyxzbodglntkumughijsc
rvefctyxzbodglnpkumawhiwsx
avefqtyvzbodglnpkumawhijsb
rfefqtyxzlodglnphumawhijsc
rvefqtyxzfowglnpkumaehijsc
rvhfvtyxzbodgqnpkumawhijsc
rfefqtyxzbodglapkumuwhijsc
rvefqclxzbodglnzkumawhijsc
qvefqtyxzbodglnckumcwhijsc
rvefqtyxzkodglnpkymawgijsc
rvefqtyxzbodgfnpkumafhizsc
rvefqtyxzbodglnxkumavhijsf
rvevqtyxzbodgpnpkurawhijsc
rvefqtyxziodglnpkubawhijss
rrefqtpxzyodglnpkumawhijsc
rvefqfyxzbodglcpkxmawhijsc
rvefdtyxzbodglnpkumvwhijsn
rverqtyxzbodglnpkwmawhijuc
rvecjtyxzboxglnpkumawhijsc
rvefqtyxzbodglnpkqmaxhifsc
rtnfqtyxzbodglnpkumawhijmc
lvefqtyxzbodelnpkumawhijsz
dvefqtyxzbbdgvnpkumawhijsc
rvefqlyhzbodglnpkumtwhijsc
roefqtyxlbodglnpkumawhyjsc
rvefqsydzjodglnpkumawhijsc
rveybtyxzbodglnpkumawhijsn
rvefqtyhzbodgvnpmumawhijsc
rvefqxyazboddlnpkumawhijsc
vvefqtyxzbohglqpkumawhijsc
reefhtyxzbodglnpkkmawhijsc
rvefqtyxzbodglnpkulowhijrc
rveqqtyxzbodgknpkumawhijsk
jvefqtqxzbodglnpkumawiijsc
rvefqtyxzboxglnpvuqawhijsc
rvefquyxzbodglwwkumawhijsc
rvefqtyxzbodnlnpkumawhgjbc
rvdfqthxdbodglnpkumawhijsc
rvefqtyxzbodllnpkumawhujsb
evefqtyxzboyglnpkumowhijsc
rvefktyxzbomglnpzumawhijsc
rvefqtyxzbodhlnnkrmawhijsc
rvefqtyxrbodglnpkujaehijsc
rvefqtyzzbodglnpkumrwhijsb
evefqtyxzpodglfpkumawhijsc
rvefqtyxibodglkpyumawhijsc
rrefqtyxzbodglnpkudawhajsc
rvifqtyxzbodglxpkumawhijlc
rxefqtyxzbedglnpkumawhijsp
rvnfqtyxzbopglnpkuqawhijsc
rvefqtyxkbodglnpoumawoijsc
dvefwtyxzbodglnpksmawhijsc
rvkfqtyxzbodglnpkdmawhijsa
rcefytyxzzodglnpkumawhijsc
rvefqtkxzbodglnpktqawhijsc
nvezqhyxzbodglnpkumawhijsc
rrefqtyxzbodgunpkumpwhijsc
rvefqtaxzbodgknpkumawhijic
pvefqtyxzbodglnpkuxawsijsc
rvefqtyxzbodglkpvumawhjjsc
wvefqtyxzkodglnpkumawhhjsc
rzefqtyxzbotglnpkumawhxjsc
rvefqtxpzbodglnpkumawzijsc
bgefqtyxzbodglnpkrmawhijsc
rvefqlyxzbodglnpkumilhijsc
cbefqtyxzbodglnpkumawhiesc
rvefqtyxzbydelnpkumahhijsc
rvefntyxzbodglnpkumaehijsw
rverqtyxztodglopkumawhijsc
rvefqtyxzdodgwrpkumawhijsc
rvefqtyxibodglnikumawhtjsc
qvafqtyxzbodglnpkurawhijsc
rvefqtyxwbodglnpaumawoijsc
rvefqtyxzoodglndknmawhijsc
rvdfqtlxzyodglnpkumawhijsc
rvefqtyxzbodglngfumawhinsc
rsefqtyxzbodglnpkumawhijek
rvoestyxzbodglnpkumawhijsc
svefqtyxzboaglnprumawhijsc
rvefqtybzbodgwnpkumawwijsc
rvefqtyxzdwdglnpkvmawhijsc
rvlfqtyxzbodglnpkrmawhixsc
rvefqtyxwbodglepkumawhijsd
rvefqtbxzbodglnqkumawhijmc
rvefqtzxzbodglnpkumuzhijsc
rvefqtyxzbodglnpkumawzwnsc
rvwfqtyxzboiglnpkumawhijsg
rtehotyxzbodglnpkudawhijsc
rvegqtyxzbodglnpyumawhijsl
rvecqtyxzbsdglnpkumawhojsc
rvefqtyxzbodmlnpkumaghijfc
rvefqtyxzxodglnpkumanvijsc
rvefqtyxzbodglnbiugawhijsc
lvefqtlxzbodglnplumawhijsc
rvefqtyxvbodglnpkumaldijsc
rmefqtyxzbodgvnpkuuawhijsc
rvefqtyxzbodglnpkymeuhijsc
rvefqtyxzuodganpsumawhijsc
rxefqtyxzbodglnpkumgwhijwc
rvefgtyxzbodglnpkudawxijsc
ahefqtyxzbodglnpkumawhejsc
rfefqtyxzbzdglnpkusawhijsc
rvefqtyszqodgljpkumawhijsc
rvefqtylzboiglnpkumrwhijsc
rvefqtyxzltdglnpkumawhijsu
rbefqtyxzbodglnpqumawhijsi
rvefqtyozpodglnpkumawhijsa
zvefqtyxzpopglnpkumawhijsc
rvefqtyxzbodglnfkqmawhijsp
rvefqtyxzbodgliakumawhijsf
rvefqtymzrodgfnpkumawhijsc
ivejqtyxzbodglnpkumawhijuc
rvefqtyxzbodflnpkxwawhijsc
dvrfqtyxzbodglnpkumashijsc
rqefqtyxzbwdglnpkumawvijsc
tvefqtkxzbodgltpkumawhijsc
rvefdtyxzbodguxpkumawhijsc
rveqqtyxvbodglnykumawhijsc
rvefqtypzcovglnpkumawhijsc
rvefqnyxzbosglnpkumdwhijsc
rvefstjxzbodslnpkumawhijsc
rvefqzyxzpodglnpkummwhijsc
rvefqkyxzbodglnhgumawhijsc
rvufqvyxzbodklnpkumawhijsc
rvefotyxzhodglnpkumawhijsk
rvefqtyxzbokglnpkumawvcjsc
lvefqtyxzbolglnpkumawoijsc
rvefqtywzoodglfpkumawhijsc
rvehqtqxzbodglnpkumawhcjsc
rqefqtyxzbodolnpkumjwhijsc
rvefqtyxzbodglrpkunawgijsc
rvefqtyxzbodglamkumawdijsc
rvefvtyzzbodllnpkumawhijsc
rvefqtyxzbldglnpfcmawhijsc
rvefppyxzbodglnpkucawhijsc
rvefquyuzbodglnpkumkwhijsc
rvefqtyxzbodgqxpkumawhivsc
rtefotyxzbodglnpkudawhijsc
rvefqtyxzbodgbnmkuzawhijsc
ivefqtyxzbodgsnpkumzwhijsc
rvhfqtyxzbodolnpkumawhijsz
rvefvtyxzbodwlnpkusawhijsc
riemqtyxzbodglnpkumawhiasc
rvtfqtyxzbqdglnpkumawuijsc
raesqtyxzbodglnpkumawhijsj
rvefqtyxzbodalmpkumawhihsc
rvefqtlxzbodgznpkkmawhijsc
rvefqbyxzbodglgpkubawhijsc
rvefqtyxnbodgxnpkumswhijsc
rvefqtyxzkodvlnukumawhijsc
rvefqtyzzbocglnpkumafhijsc
rvhfqtyxzbodglmpkumgwhijsc
rvsfrtyxzbodnlnpkumawhijsc
rvefqtyxzbxdglnpkujcwhijsc
rvefqtyvzrodglnphumawhijsc
reetatyxzbodglnpkumawhijsc
rvefqtyxzbodglnpzumaoqijsc
ovefqtyyzbodglnvkumawhijsc
rvefqbyxzbodnlnpkumawhijsi
xvefqtyxzbodgrnpkumawrijsc
rvebqtyxzbodglnpkumazhiasc
rqeretyxzbodglnpkumawhijsc
rvefqtyxzyodglapkumvwhijsc
rvesqxyxzbodglnpvumawhijsc
rvefqtyxeborglnpkufawhijsc
rvecqtyxzbodflnpkumawnijsc
rvefdpyxtbodglnpkumawhijsc
rvefqtyfzbodclnpkymawhijsc
rvefqtywzbodglnpxumawhiusc
rvefqtyxzbodglnpkumawzbjwc
rvewqtyxdbodglnpxumawhijsc
rvefqtyxzgocglnpkgmawhijsc
rvufqtyxzbodggnpkuzawhijsc
rvefqtynzlodgllpkumawhijsc
rvedqtyxzbodghnpkumawhujsc
rvefqtyxlbodgnnpkpmawhijsc
rvefqtyxzboqglnpkzmawhijec
rvefqtyxzbodglnpkfmwwyijsc
rwefqtkxzbodzlnpkumawhijsc
rvefqtyxvbodglnpkufawhyjsc
rvefqtyxzbodgltpkumawhqmsc
rvefctyxzbodglfpkumathijsc
rvefqtyxzbodgfnpkuuawhijfc
rvefqttxzbodglnpmumawhijwc
rvefqtyxzbodglnpkqmawhihsj
rvefqtyxzbsdglcnkumawhijsc
rvbiqtyxzbodglnpkumawhijlc
rnefqtylzvodglnpkumawhijsc
mvefqtyxzbddglnpkumcwhijsc
rvefwtyxzbodglnpkgmawhijxc
rvefqtyxljodglnpkumxwhijsc
rvefqtyxzbodglnpkuprwhijsd
rcxfqtyxzbldglnpkumawhijsc
rvetqtyxzbojglnpkumewhijsc
rvxfqtyxzbtdglnpkbmawhijsc